train_halt_head: False
halt_exploration_prob: 0.1
halt_max_steps: 8

H_cycles: 2
L_cycles: 2

H_layers: 4
L_layers: 4

hidden_size: 64
num_heads: 2  # min(2, hidden_size // 64)
expansion: 4

puzzle_emb_ndim: ${.hidden_size}

pos_encodings: rope
